import { iQuestionForm } from "@/types/question";

export const defaultQuestions: iQuestionForm[] = [
    {
        type: "frequency",
        title: "Atende as regras",
        value: "",
        order: 1,
    },
    {
        type: "frequency",
        title: "Socializa com o grupo",
        value: "",
        order: 2,
    },
    {
        type: "frequency",
        title: "Isola-se do grupo",
        value: "",
        order: 3,
    },
    {
        type: "frequency",
        title: "Possui tolerância a frustração",
        value: "",
        order: 4,
    },
    {
        type: "frequency",
        title: "Respeita colega e professores",
        value: "",
        order: 5,
    },
    {
        type: "frequency",
        title: "Faz relatos fantasiosos",
        value: "",
        order: 6,
    },
    {
        type: "frequency",
        title: "Concentra-se nas atividades",
        value: "",
        order: 7,
    },
    {
        type: "frequency",
        title: "Tem iniciativa",
        value: "",
        order: 8,
    },
    {
        type: "frequency",
        title: "Sonolência durante as atividades em sala de aula",
        value: "",
        order: 9,
    },
    {
        type: "frequency",
        title: "Alterações intensas de humor",
        value: "",
        order: 10,
    },
    {
        type: "frequency",
        title: "Indica oscilação repentina de humor",
        value: "",
        order: 11,
    },
    {
        type: "frequency",
        title: "Irrita-se com facilidade",
        value: "",
        order: 12,
    },
    {
        type: "frequency",
        title: "Ansiedade",
        value: "",
        order: 13,
    },
    {
        type: "frequency",
        title: "Escuta quando seus colegas falam",
        value: "",
        order: 14,
    },
    {
        type: "frequency",
        title: "Escuta e segue orientação dos professores",
        value: "",
        order: 15,
    },
    {
        type: "frequency",
        title: "Mantem-se em sala de aula",
        value: "",
        order: 16,
    },
    {
        type: "frequency",
        title: "Desloca-se muito na sala",
        value: "",
        order: 17,
    },
    {
        type: "frequency",
        title: "Fala demasiadamente",
        value: "",
        order: 18,
    },
    {
        type: "frequency",
        title: "É pontual",
        value: "",
        order: 19,
    },
    {
        type: "frequency",
        title: "É assíduo",
        value: "",
        order: 20,
    },
    {
        type: "frequency",
        title: "Demonstra desejo de trabalhar",
        value: "",
        order: 21,
    },
    {
        type: "frequency",
        title: "Apropria-se indevidamente daquilo que não é seu",
        value: "",
        order: 22,
    },
    {
        type: "frequency",
        title: "Indica hábito de banho diário",
        value: "",
        order: 23,
    },
    {
        type: "frequency",
        title: "Indica habito de escovação e qualidade na escovação",
        value: "",
        order: 24,
    },
    {
        type: "frequency",
        title: "Indica cuidado com a aparência e limpeza do uniforme",
        value: "",
        order: 25,
    },
    {
        type: "frequency",
        title: "Indica autonomia quanto a estes hábitos (23, 24, 25)",
        value: "",
        order: 26,
    },
    {
        type: "frequency",
        title: "Indica falta do uso de medicação com oscilações de comportamento",
        value: "",
        order: 27,
    },
    {
        type: "frequency",
        title: "Tem meio articulado de conseguir receitas e aquisições das medicações",
        value: "",
        order: 28,
    },
    {
        type: "frequency",
        title: "Traz seus materiais organizados",
        value: "",
        order: 29,
    },
    {
        type: "frequency",
        title: "Usa transporte coletivo",
        value: "",
        order: 30,
    },
    {
        type: "frequency",
        title: "Tem iniciativa diante das atividades propostas",
        value: "",
        order: 31,
    },
    {
        type: "frequency",
        title: "Localiza-se no espaço da Instituição",
        value: "",
        order: 32,
    },
    {
        type: "frequency",
        title: "Situa-se nas trocas de sala e atividades",
        value: "",
        order: 33,
    },
    {
        type: "frequency",
        title: "Interage par a par",
        value: "",
        order: 34,
    },
    {
        type: "frequency",
        title: "Interage em grupo",
        value: "",
        order: 35,
    },
    {
        type: "frequency",
        title: "Cria conflitos e intrigas",
        value: "",
        order: 36,
    },
    {
        type: "frequency",
        title: "Promove a harmonia",
        value: "",
        order: 37,
    },
    {
        type: "frequency",
        title: "Faz intrigas entre colegas x professores",
        value: "",
        order: 38,
    },
    {
        type: "frequency",
        title: "Demonstra interesse em participar das atividades extraclasses",
        value: "",
        order: 39,
    },
    {
        type: "frequency",
        title: "Você percebe que existe interação/participação da família em apoio ao usuário na Instituição",
        value: "",
        order: 40,
    },
    {
        type: "frequency",
        title: "Você percebe superproteção por parte da família quanto a autonomia do usuário",
        value: "",
        order: 41,
    },
    {
        type: "frequency",
        title: "Usuário traz relatos negativos da família (de forma geral)",
        value: "",
        order: 42,
    },
    {
        type: "frequency",
        title: "Usuário traz relatos positivos da família (de forma geral)",
        value: "",
        order: 43,
    },
    {
        type: "frequency",
        title: "Você percebe incentivo quanto a busca de autonomia para o usuário por parte da família",
        value: "",
        order: 44,
    },
    {
        type: "frequency",
        title: "Você percebe incentivo quanto a inserção do usuário no mercado de trabalho por parte da família",
        value: "",
        order: 45,
    },
    {
        type: "frequency",
        title: "Traz os documentos enviados pela Instituição assinado",
        value: "",
        order: 46,
    },
    {
        type: "textarea",
        title: "Em sua opinião o usuário tem perfil para esta instituição? Por quê?",
        value: "",
        order: 47,
    },
    {
        type: "textarea",
        title: "Em que situações demonstra irritações?",
        value: "",
        order: 48,
    },
    {
        type: "textarea",
        title: "Observações",
        value: "",
        order: 49,
    },
];;